<?php
// action="http://localhost:8000/adicionar_usuario" method="post"

foreach( $this->view->dados  as $data){
   var_dump($data);
    echo"<br/>";
}
?>
<div class="container ">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-10 shadow-lg p-3 mb-5 bg-body rounded ">
            <h1>Cadastro </h1>
            <form id="form_cadastro" onsubmit="sendFormulario(event)">

                <div class="col-12 p-1">
                    <label for="nome" class="form-label">Nome</label>
                    <input type="text" class="form-control " id="nome" aria-describedby="nome" name="nome" value="">
                    <div id="nomeFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" class="form-control" id="email" aria-describedby="email" name="email">
                    <div id="emailFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>

                <div class="d-flex flex-row ">
                    <div class="col-md-6 p-1">
                        <label for="senha" class="form-label">Senha</label>
                        <input type="text" class="form-control" id="senha" name="senha">
                        <div id="senhaFeedback" class="invalid-feedback"></div>
                        <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                    </div>

                    <div class="col-md-6 p-1 ">
                        <label for="senha_confirma" class="form-label">Confrime a senha</label>
                        <input type="text" class="form-control" id="senha_confirma">
                        <div id="senha_confrimaFeedback" class="invalid-feedback"></div>
                    </div>
                </div>
                <div class="d-flex flex-row ">
                    <div class="col-md-6 p-1">
                        <label for="senha" class="form-label">Status</label>
                        <input type="text" class="form-control" id="senha" name="senha">
                        <div id="senhaFeedback" class="invalid-feedback"></div>
                        <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                    </div>

                    <div class="col-md-6 p-1 ">
                        <label for="senha_confirma" class="form-label">Usuario tipo</label>
                        <input type="text" class="form-control" id="senha_confirma">
                        <div id="senha_confrimaFeedback" class="invalid-feedback"></div>
                    </div>
                </div>

                <div class="float-end"><button type="submit" class="btn btn-primary mt-3" id="bnt_cadastro"><span hidden
                            id="btn_load" class="spinner-border spinner-border-sm" role="status"
                            aria-hidden="true"></span>Avançar</button></div><br><br>
            </form>
        </div>
    </div>
<div>


        <script src="/js/usuario.js"></script>