<?php
// action="http://localhost:8000/adicionar_usuario" method="post"

?>

<div class="container ">
<!--Toast-->
<div class="container">
        <div class="row">
            <div class="toast" role="alert" data-animation="true" data-autohide="false" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                <img src="https://picsum.photos/id/200/30/30" class="rounded me-2" alt="...">
                <strong class="mr-auto">Bootstrap</strong>
                <small>11 mins ago</small>
                <button type="button" class="btn-close ml-2 mb-1 close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                Hello Sarthak
                </div>
            </div>
        </div>
    </div>
<!--Toast End-->
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-10 shadow-lg p-3 mb-5 bg-body rounded ">
            <h1>Cadastro </h1>
            <form id="form_cadastro" onsubmit="sendFormulario(event)">

                <div class="col-12 p-1">
                    <label for="nome" class="form-label">Nome</label>
                    <input type="text" class="form-control " id="nome" aria-describedby="nome" name="nome" value="">
                    <div id="nomeFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" class="form-control" id="email" aria-describedby="email" name="email">
                    <div id="emailFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>

                <div class="d-flex flex-row ">
                    <div class="col-6 p-1">
                        <label for="senha" class="form-label">Senha</label>
                        <input type="text" class="form-control" id="senha" name="senha">
                        <div id="senhaFeedback" class="invalid-feedback"></div>
                        <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                    </div>

                    <div class=" col-6 p-1 ">
                        <label for="senhaConfirma" class="form-label">Confrime a senha</label>
                        <input type="text" class="form-control" id="senhaConfirma">
                        <div id="senhaConfirmaFeedback" class="invalid-feedback"></div>
                       
                    </div>
                    
                </div>
                <div class="d-flex flex-row " id="div_alert">
                    <div class=" col-12 p-1">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert" >
                            <strong>Senhas devem ser iguais</strong>                          
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row ">
                    <div class="col-6 p-1">
                        <label for="status" class="form-label">Status</label>
                        <select id="status" name="status" class="form-select" aria-label="Default select example">
                          <?php foreach($this->view->dados['status'] as $tipo){  ?>
                              <option value="<?php echo $tipo['id'] ?>"><?php echo $tipo['sta_nome'] ?></option>
                           <?php };  ?>
                        </select>
                    </div>

                    <div class="col-6 p-1 ">
                        <label for="usuario_tipo" class="form-label">Usuario tipo</label>
                        <select  id="usuario_tipo" name="usuario_tipo"class="form-select" aria-label="Default select example">
                            <?php foreach($this->view->dados['usuario_tipo'] as $tipo){  ?>
                              <option value="<?php echo $tipo['usut_id'] ?>"><?php echo $tipo['usut_nome'] ?></option>
                            <?php };  ?>
                           
                        </select>
                    </div>
                </div>

                <div class="float-end"><button type="submit" class="btn btn-primary mt-3" id="bnt_cadastro"><span hidden
                            id="btn_load" class="spinner-border spinner-border-sm" role="status"
                            aria-hidden="true"></span>Avançar</button></div><br><br>
            </form>
        </div>
    </div>
<div>


        <script src="/js/usuario.js"></script>