<div class="container ">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-4 shadow-lg p-3 mb-5 bg-body rounded ">
            <h1>Login</h1>
            <form>
                <div class="mb-3 col-md-12">
                    <label for="exampleInputEmail1" class="form-label">Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                 <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="mb-3 col-md-12">
                    <label for="exampleInputPassword1" class="form-label">Senha</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="float-end"><button type="submit" class="btn btn-primary">Enviar</button></div><br><br>
               
              
            </form>
            <div class="float-start"><a  href="#" >Esqueceu a senha?</a></div>
        </div>
    </div>
 <div>