<div id="alertToast" class="toast  position-absolute   text-white bg-success" role="alert"
    aria-live="assertive" aria-atomic="true" style="z-index: 11">
    <div class="d-flex">
        <div class="toast-body">
            <div id="txt-toast-alert"></div>
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
</div>
<!--  este compomente e manupulado pelo js  exemplo no categorias.js função toast() -->