<div id="alertToastPrinical" class="toast  position-absolute   text-white bg-success m-2" role="alert"
    aria-live="assertive" aria-atomic="true" style="z-index: 11 position: absolute; top: 0; right: 0;">
    <div class="d-flex">
        <div class="toast-body">
            <div id="txt-toast-alert-principal"></div>
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
</div>
<!-- toast tela principal -->