<?php include("menu_adm.phtml"); ?>

<div class="container" tabindex="-1">

    <script src="../js/categorias.js"></script>

    <div class="bg-light shadow p-3 mb-4 mt-4 bg-body rounded">
        <?php include("templates/toastAlert.phtml"); ?>
        <nav class="navbar  bg-light  p-1 mb-3 bg-body rounded">
            <h4>Gerenciamento das Categorias</h4>
            <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasRight-categoria" aria-controls="offcanvasRight-categoria">Adicionar</button>
        </nav>
        
        <!-- inicio data table-->
        <table class="table table-hover table-responsive" id="categoria" style="width:100%">
            <thead>
                <tr>
                    <th scope="col" id="cat_id">Id</th>
                    <th scope="col" id="cat_nome">Nome</th>
                    <th scope="col" id="cat_descricao">Descrição</th>
                    <th scope="col" id="acao">Ações</th>
                </tr>
            </thead>
        </table>
        <!-- fim data table-->
    </div>

    <div class="offcanvas offcanvas-end shadow  bg-body rounded border border-0 " data-bs-backdrop="false" tabindex="-1"
        id="offcanvasRight-categoria" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">

            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body pt-4">
            <form class="pt-2" onsubmit="sendFormulario(event)">
                <h5>Cadastro categoria</h5>
                <div class="col-12 p-1">
                    <label for="nome" class="form-label">Nome</label>
                    <input type="text" class="form-control " id="nome" aria-describedby="nome" name="nome" value="">
                    <div id="nomeFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <label for="descricao" class="form-label">Descrição</label>
                    <input type="text" class="form-control " id="descricao" aria-describedby="descricao"
                        name="descricao" value="">
                    <div id="descricaoFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>

            </form>
        </div>
    </div>
  
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasEditar-categoria" data-bs-backdrop="false"
        aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header pt-4">
            <button type="button" class="btn-close" onclick="closeCanva()" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">

            <form class="pt-2" onsubmit="saveCategoriaEditada()">
                <h5>Edição categoria</h5>
                <div class="col-12 p-1">
                    <label for="cat_id_edit" class="form-label">ID </label>
                    <input type="text" class="form-control " id="cat_id_edit" aria-describedby="cat_id" name="cat_id"
                        value="" disabled>
                    <div id="nomeFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <label for="cat_nome" class="form-label">Nome</label>
                    <input type="text" class="form-control " id="cat_nome_edit" aria-describedby="cat_nome"
                        name="cat_nome" value="">
                    <div id="cat_nomeFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <label for="cat_descricao" class="form-label">Descrição</label>
                    <input type="text" class="form-control " id="cat_descricao_edit" aria-describedby="cat_descricao"
                        name="descricao" value="">
                    <div id="descricaoFeedback" class="invalid-feedback"></div>
                    <!--   <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                </div>
                <div class="col-12 p-1">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>

            </form>


        </div>
    </div>
</div>